# This workflow will build AOT CLI for all supported systems

name: .NET publish cli

on:
  push:
     tags:
      - cli-*
  workflow_dispatch:

jobs:
  buildaots:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Publish Windows x64
      run: dotnet publish -r win-x64 -c Release -o win-x64
      working-directory: cli
      if: matrix.os == 'windows-latest'
    - uses: actions/upload-artifact@v4
      if: matrix.os == 'windows-latest'
      with:
        name: codec8cli-win64
        path: cli/win-x64
        compression-level: 9 # maximum compression

    - name: Publish Linux x64
      run: dotnet publish -r linux-x64 -c Release -o linux-x64
      working-directory: cli
      if: matrix.os == 'ubuntu-latest'
    - uses: actions/upload-artifact@v4
      if: matrix.os == 'ubuntu-latest'
      with:
        name: codec8cli-linux64
        path: cli/linux-x64
        compression-level: 9 # maximum compression

    - name: Publish Mac arm64
      run: dotnet publish -r osx-arm64 -c Release -o osx-arm64
      working-directory: cli
      if: matrix.os == 'macos-latest'
    - uses: actions/upload-artifact@v4
      if: matrix.os == 'macos-latest'
      with:
        name: codec8cli-macarm64
        path: cli/osx-arm64
        compression-level: 9 # maximum compression

